version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 10
    ignore:
      # Manually update stylelint and prettier, to ensure we control the range
      # of version that we maintain support for
      - dependency-name: 'stylelint'
      - dependency-name: 'prettier'
      - dependency-name: 'prettier-linter-helpers'
      # Strip ansi v7 is esm only, lets not rewrite tests just to deal with that
      - dependency-name: 'strip-ansi'
    groups:
      dev-dependencies:
        dependency-type: development
        patterns:
          - '*'
