version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 10
    ignore:
      # Manually update stylelint and prettier, to ensure we control the range
      # of version that we maintain support for
      - dependency-name: 'stylelint'
      - dependency-name: 'prettier'
      - dependency-name: 'prettier-linter-helpers'
      # strip-ansi v7 is esm only, lets not rewrite tests just to deal with that
      - dependency-name: 'strip-ansi'
      # eslint-plugin-n v16 drops support for node 14, keep this till we drop
      # support too
      - dependency-name: 'eslint-plugin-n'
    groups:
      dev-dependencies:
        dependency-type: development
        patterns:
          - '*'
